### ISSUE TITLE
Initial setup of the project

### ISSUE THREAD

**Issue by ges134** [CloeD/wannabe-deviant-art#1]
Make the setup of the project using the following dependencies:

- express
- morgan
- pug
- body-parser

And the following dev dependencies.
- ts-node
- @types/body-parser
- @types/express
- @types/morgan
- @types/node
- jest
- nodemon
- supertest
- @types/supertest
- ts-jest
- ts-node
- typescript

**Comment by CloeD** [comment]
Done. What's next ?

**Comment by ges134** [comment]
Installing packages is not really enough for a setup, the least to do would have to obtain a runnable application with npm start or npm dev
